#!/usr/bin/env Rscript

BuildGallery <- function(path=".") {
  file.names <- list.files("./img", "*.png$")
  if (length(file.names) == 0) stop("no png images found")
  base.names <- tools::file_path_sans_ext(file.names)

  con <- file(file.path(path, "Gallery.md"))
  on.exit(close(con))

  FUN <- function(i) {
    sprintf("### %s\n\n![](./img/%s)\n\n---\n", base.names[i], file.names[i])
  }
  s <- vapply(seq_along(file.names), FUN, "")
  cat(s, file=con, sep="\n")

  invisible(NULL)
}

BuildGallery(".")
